# Generated by Django 3.2 on 2024-01-31 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='titie',
            new_name='title',
        ),
    ]
